FROM apache/airflow:3.1.3-python3.10

LABEL Author="Bhupinderjit Singh"
LABEL Description="Airflow + PySpark + Java 17" 
LABEL Version=1.0

USER root

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    openjdk-17-jdk \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

USER airflow

RUN pip3.10 install --no-cache-dir \
    pyspark==3.4.0 \
    apache-airflow-providers-apache-spark

WORKDIR /opt/airflow
